> composer create-project nouvu/framework Nouvu-Test "v1.0.1-alpha"

C:\GitHub\Nouvu-Framework\service.php
C:\GitHub\Nouvu-Framework\readme.php
C:\GitHub\Nouvu-Framework\Nouvu\Components\Config\Repository.php
C:\GitHub\Nouvu-Framework\Nouvu\Foundation\Application.php
C:\GitHub\Nouvu-Framework\Nouvu\Foundation\Table\ContextAble.php
C:\GitHub\Nouvu-Framework\Nouvu\Foundation\Table\CollectAble.php
C:\GitHub\Nouvu-Framework\Nouvu\Foundation\Table\App.php
C:\GitHub\Nouvu-Framework\Nouvu\Foundation\User\Model.php
C:\GitHub\Nouvu-Framework\Nouvu\Http\Kernel.php
C:\GitHub\Nouvu-Framework\Nouvu\Http\Controllers\KernelController.php
C:\GitHub\Nouvu-Framework\Nouvu\Http\Controllers\InputController.php
C:\GitHub\Nouvu-Framework\Nouvu\Http\Controllers\BaseController.php
C:\GitHub\Nouvu-Framework\Nouvu\Routing\UrlMatcher.php
C:\GitHub\Nouvu-Framework\Nouvu\Routing\Router.php
C:\GitHub\Nouvu-Framework\Nouvu\Routing\RouteCollection.php
C:\GitHub\Nouvu-Framework\Nouvu\Routing\RequestContext.php
C:\GitHub\Nouvu-Framework\Nouvu\View\Viewer.php
C:\GitHub\Nouvu-Framework\Nouvu\View\Terminal.php
C:\GitHub\Nouvu-Framework\Nouvu\View\Builder\ShortTag.php
C:\GitHub\Nouvu-Framework\Nouvu\View\Builder\CreateHtml.php
C:\GitHub\Nouvu-Framework\Nouvu\View\Builder\Content.php
C:\GitHub\Nouvu-Framework\Nouvu\View\Repository\TitleRepository.php
C:\GitHub\Nouvu-Framework\Nouvu\View\Repository\HeadRepository.php
C:\GitHub\Nouvu-Framework\Nouvu\View\Repository\CommitRepository.php
C:\GitHub\Nouvu-Framework\userdata\tools.php
C:\GitHub\Nouvu-Framework\userdata\Configs\viewer.php
C:\GitHub\Nouvu-Framework\userdata\Configs\router.php
C:\GitHub\Nouvu-Framework\userdata\Configs\config.php
C:\GitHub\Nouvu-Framework\userdata\Configs\app.php
C:\GitHub\Nouvu-Framework\userdata\Resources\Controllers\MainController.php
C:\GitHub\Nouvu-Framework\userdata\Resources\Models\MainModel.php
C:\GitHub\Nouvu-Framework\userdata\Resources\System\RecreateRouting.php
C:\GitHub\Nouvu-Framework\userdata\Resources\View\default\welcome.php
C:\GitHub\Nouvu-Framework\userdata\Resources\View\default\index.php
C:\GitHub\Nouvu-Framework\userdata\Resources\View\default\error.500.php
C:\GitHub\Nouvu-Framework\userdata\Resources\View\default\error.404.php
C:\GitHub\Nouvu-Framework\userdata\Resources\View\default\error-template.php
C:\GitHub\Nouvu-Framework\userdata\Resources\View\default\default-template.php
