composer create-project nouvu/framework Nouvu-Framework "v2.0.0-alpha"

Nouvu-Framework\service.php
Nouvu-Framework\readme.php
Nouvu-Framework\src\Nouvu\Component\Config\Repository.php
Nouvu-Framework\src\Nouvu\Component\Database\DatabaseToolsInterface.php
Nouvu-Framework\src\Nouvu\Component\Database\DatabaseRequestInterface.php
Nouvu-Framework\src\Nouvu\Component\Database\DatabaseManager.php
Nouvu-Framework\src\Nouvu\Component\Database\Components.php
Nouvu-Framework\src\Nouvu\Component\Security\_FirewallAwareRememberMeHandler.php
Nouvu-Framework\src\Nouvu\Component\Security\_DecoratedRememberMeHandler.php
Nouvu-Framework\src\Nouvu\Component\Security\TokenBasedRememberMeServices.php
Nouvu-Framework\src\Nouvu\Component\Security\NouvuAuthenticationHandler.php
Nouvu-Framework\src\Nouvu\Component\Security\Core\User\__DatabaseAuthenticationProvider.php
Nouvu-Framework\src\Nouvu\Component\Security\Core\User\DatabaseUserProvider.php
Nouvu-Framework\src\Nouvu\Component\Security\Core\User\DatabaseTokenProvider.php
Nouvu-Framework\src\Nouvu\Component\Validator\Validation.php
Nouvu-Framework\src\Nouvu\Component\Validator\Exception\ViolationsException.php
Nouvu-Framework\src\Nouvu\Component\Validator\Exception\RuntimeException.php
Nouvu-Framework\src\Nouvu\Component\Validator\Exception\InvalidMethodException.php
Nouvu-Framework\src\Nouvu\Foundation\ApplicationTrait.php
Nouvu-Framework\src\Nouvu\Foundation\Application.php
Nouvu-Framework\src\Nouvu\Http\Kernel.php
Nouvu-Framework\src\Nouvu\Http\Controllers\KernelController.php
Nouvu-Framework\src\Nouvu\Http\Controllers\InputController.php
Nouvu-Framework\src\Nouvu\Http\Controllers\AbstractController.php
Nouvu-Framework\src\Nouvu\Routing\UrlMatcher.php
Nouvu-Framework\src\Nouvu\Routing\Router.php
Nouvu-Framework\src\Nouvu\Routing\RouteCollection.php
Nouvu-Framework\src\Nouvu\Routing\RequestContext.php
Nouvu-Framework\src\Nouvu\Routing\ContextTrait.php
Nouvu-Framework\src\Nouvu\Routing\CollectionTrait.php
Nouvu-Framework\src\Nouvu\View\Viewer.php
Nouvu-Framework\src\Nouvu\View\Terminal.php
Nouvu-Framework\src\Nouvu\View\Builder\ShortTag.php
Nouvu-Framework\src\Nouvu\View\Builder\Content.php
Nouvu-Framework\src\Nouvu\View\Builder\BuilderHtml.php
Nouvu-Framework\src\Nouvu\View\Repository\TitleRepository.php
Nouvu-Framework\src\Nouvu\View\Repository\HeadRepository.php
Nouvu-Framework\src\Nouvu\View\Repository\CommitRepository.php
Nouvu-Framework\userdata\tools.php
Nouvu-Framework\userdata\Configs\viewer.php
Nouvu-Framework\userdata\Configs\validator.php
Nouvu-Framework\userdata\Configs\security.php
Nouvu-Framework\userdata\Configs\router.php
Nouvu-Framework\userdata\Configs\query.php
Nouvu-Framework\userdata\Configs\database.php
Nouvu-Framework\userdata\Configs\config.php
Nouvu-Framework\userdata\Configs\auth.php
Nouvu-Framework\userdata\Configs\app.php
Nouvu-Framework\userdata\Resources\Controllers\RegistrationController.php
Nouvu-Framework\userdata\Resources\Controllers\MainController.php
Nouvu-Framework\userdata\Resources\Controllers\AuthController.php
Nouvu-Framework\userdata\Resources\Entity\User.php
Nouvu-Framework\userdata\Resources\Models\MainModel.php
Nouvu-Framework\userdata\Resources\Models\AbstractModel.php
Nouvu-Framework\userdata\Resources\Models\Auth\LostModel.php
Nouvu-Framework\userdata\Resources\Models\Auth\LoginModel.php
Nouvu-Framework\userdata\Resources\Models\Auth\ForgotModel.php
Nouvu-Framework\userdata\Resources\Models\Registration\RegistrationModel.php
Nouvu-Framework\userdata\Resources\Models\Registration\ConfirmModel.php
Nouvu-Framework\userdata\Resources\Models\Traits\GetRequestUsername.php
Nouvu-Framework\userdata\Resources\Models\Traits\GetRequestSecondPassword.php
Nouvu-Framework\userdata\Resources\Models\Traits\GetRequestPassword.php
Nouvu-Framework\userdata\Resources\Models\Traits\GetRequestLogin.php
Nouvu-Framework\userdata\Resources\Models\Traits\GetRequestFirstPassword.php
Nouvu-Framework\userdata\Resources\Models\Traits\GetRequestEmail.php
Nouvu-Framework\userdata\Resources\Models\Traits\GetQueryConfirm.php
Nouvu-Framework\userdata\Resources\System\RecreateRouting.php
Nouvu-Framework\userdata\Resources\System\MailerFacade.php
Nouvu-Framework\userdata\Resources\System\LermaFacade.php
Nouvu-Framework\userdata\Resources\View\default\welcome.php
Nouvu-Framework\userdata\Resources\View\default\index.php
Nouvu-Framework\userdata\Resources\View\default\error.500.php
Nouvu-Framework\userdata\Resources\View\default\error.404.php
Nouvu-Framework\userdata\Resources\View\default\error-template.php
Nouvu-Framework\userdata\Resources\View\default\default-template.php
Nouvu-Framework\userdata\Resources\View\default\user\register.php
Nouvu-Framework\userdata\Resources\View\default\user\register-success.php
Nouvu-Framework\userdata\Resources\View\default\user\register-confirm.php
Nouvu-Framework\userdata\Resources\View\default\user\lost-password.php
Nouvu-Framework\userdata\Resources\View\default\user\lost-password-success.php
Nouvu-Framework\userdata\Resources\View\default\user\login.php
Nouvu-Framework\userdata\Resources\View\default\user\form-template.php
Nouvu-Framework\userdata\Resources\View\default\user\forgot-password.php
Nouvu-Framework\userdata\Resources\View\default\user\forgot-password-mail.php